### ISSUE TITLE
Missing app icon :gear: 

### ISSUE THREAD

**Issue by madsrh** [ubuntu-flutter-community/settings#117]
Once done, this settings app will be fantastic and so it should have a beautiful icon. 
@Feichtmeier if you aren't planing on reusing/refurbishing an existing icon, perhaps we should summoning @ubuntujaggers :mage_man:

**Comment by Feichtmeier** [comment]
hehe ^^
well I would love to take the settings app icon and even replace GCC in Ubuntu.

Currently I only start the app from within vscode but this is a very good point and we should take care of actually having a .desktop file and icon and all this production stuff!

**Comment by Feichtmeier** [comment]
It's actually only a .desktop file that is missing
and ofc some way to package the app ... as a... snap?

![grafik](https://user-images.githubusercontent.com/15329494/135761455-96098ee9-1918-4ae0-b4de-75299bc4407c.png)

**Comment by Feichtmeier** [comment]
this will be fixed with #127
