### ISSUE TITLE
Idea/discussion: Add "solid color" option for background

### ISSUE THREAD

**Issue by madsrh** [ubuntu-flutter-community/settings#135]
I know a lot of people just want a plain black background, so it might be worth adding an option to use a solid color. I'm not sure how the interface should look, but I've been looking at old [Ubuntu ](https://www.omgubuntu.co.uk/wp-content/uploads/2012/04/Screen-Shot-2012-04-26-at-13.42.jpg)and [XFCE ](https://docs.xfce.org/_media/xfce/xfdesktop/4.11/xfdesktop_scrsh16.png)screenshots as inspiration.

This mockup uses radio buttons, but I've seen the same thing in [Windows 11](https://www.intowindows.com/wp-content/uploads/2021/08/change-Windows-11-wallpaper-pic4_thumb.jpg) with a dropdown menu 🔽 

![image](https://user-images.githubusercontent.com/3986894/136105673-6ea01350-6dcb-431a-9e1f-c1d951aa3b41.png)

This isn't thought through, but hopefully you get the idea 😅 

![image](https://user-images.githubusercontent.com/3986894/136107183-b87c5ea8-e8a0-40c0-82ea-fd08dfc12c78.png)

**Comment by Feichtmeier** [comment]
Very nice @madsrh , thank you <3

**Comment by Feichtmeier** [comment]
Would it be ok if we put the color selection into a dialog instead?
