### ISSUE TITLE
Wallpaper page: add an option to use the current wallpaper of the day (Google Earth, Bing, NASA)

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu-flutter-community/settings#189]
~~Use Google earth wallpaper of the day~~
- [x] Use Microsoft Bing wallpaper of the day #215
- [x] Use NASA wallpaper of the day
- [x] #385

~~- eventually install a dart demon process to automatically update it after a certain period~~ <- this is too complicated for our project

**Comment by madsrh** [comment]
Nice 👌

**Comment by YoussefLasheen** [comment]
Can I be assigned this issue?
I already made a pull request

**Comment by Feichtmeier** [comment]
@YoussefLasheen thanks for working on this!
Will review it as soon as I can!

**Comment by YoussefLasheen** [comment]
About the google earth daily wallpaper requirement. 

I can only find this website https://earthview.withgoogle.com/
But its API doesn't have a daily image type of feature. You have to know the id of the image to access it.
Extensions like this https://extensions.gnome.org/extension/1295/google-earth-wallpaper/
store a curated list of ids and shuffle between them.
That kind of provider would require custom business logic and would not fit in the current model.

**Comment by Feichtmeier** [comment]
@YoussefLasheen alright! Thanks for investigating! Then let's remove this from the list, this page is already feature-packed 💪 Thanks to you!
