### ISSUE TITLE
WallpaperPage: too much memory allocated and only slightly freed

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu-flutter-community/settings#231]
It looks like the wallpaper page is not correctly "freeing up memory space" after closing it.
Every time it is reloaded the memory grows by about 150 MB. It slowly shrinks but it is def. too slow.

Any idea why this is happening @jpnurmi ?
![ya](https://user-images.githubusercontent.com/15329494/148366730-22fc5ae7-c042-4c67-89d2-da9dd00f6451.gif)

**Comment by jpnurmi** [comment]
AFAIK, the OS doesn't reclaim unused memory from the process immediately if there's no need to. Because of that, you cannot use a process manager to monitor effective memory usage. You can use [DevTools](https://docs.flutter.dev/development/tools/devtools/overview) to profile memory usage.

**Comment by Feichtmeier** [comment]
> AFAIK, the OS doesn't reclaim unused memory from the process immediately if there's no need to. Because of that, you cannot use a process manager to monitor effective memory usage. You can use [DevTools](https://docs.flutter.dev/development/tools/devtools/overview) to profile memory usage.

ok
eventually I could fetch the images at the first page load via a service and then only update those images when something changes :thinking:

**Comment by Feichtmeier** [comment]
https://github.com/flutter/flutter/issues/62107

It may be not a bug but rather a too excessive use of Image.file()
Since every image is loaded into memory

Reducing the cacheheight improves the situation a bit. But a settings app allocating 800+ mb on certain pages is far from optimal :(

**Comment by Feichtmeier** [comment]
> . Because of that, you cannot use a process manager to monitor effective memory usage. You can use [DevTools](https://docs.flutter.dev/development/tools/devtools/overview) to profile memory usage.

For some reason my devtools crash with 
```
Unhandled exception:
type 'DillSetterBuilder' is not a subtype of type 'SourceMemberBuilderImpl?' in type cast
#0      SourceLibraryBuilder.checkMemberConflicts.<anonymous closure> (package:front_end/src/fasta/source/source_library_builder.dart:998:22)
#1      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:574:13)
#2      Scope.forEachLocalSetter (package:front_end/src/fasta/scope.dart:424:14)
#3      SourceLibraryBuilder.checkMemberConflicts (package:front_end/src/fasta/source/source_library_builder.dart:974:11)

```
I try in a vm if this is related to my installation

**Comment by Feichtmeier** [comment]
not anymore
around 100mb
