### ISSUE TITLE
Accessibility key not found

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu-flutter-community/settings#243]
Several keys are not found including screen keyboard and mouse keys

CC @mivoligo

**Comment by mivoligo** [comment]
Can you give more details, please?

**Comment by Feichtmeier** [comment]
When clicking "Mouse keys":

```
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Key keyboard/mousekeys-enable not in GSettings schema org.gnome.desktop.a11y
#0      GSettings._getSchemaEntry
package:gsettings/src/gsettings.dart:170
#1      GSettings.get
package:gsettings/src/gsettings.dart:90
<asynchronous suspension>
```

When Clicking "simulated secondary click" in the click assist dialog
```
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Key mouse/secondary-click-enabled not in GSettings schema org.gnome.desktop.a11y
#0      GSettings._getSchemaEntry
package:gsettings/src/gsettings.dart:170
#1      GSettings.get
package:gsettings/src/gsettings.dart:90
<asynchronous suspension>
```
Same for screen keyboard
Etc

It looks to me that org.gnome.desktop.a11y changed its name or its keys

**Comment by mivoligo** [comment]
I have the same error messages but those settings still seem to work
properly. I'll have another look later on.

**Comment by mivoligo** [comment]
I had a look today and I can't find the problem. It reads the values properly, changes them when changed from the app or from an external app like Dconf or Gnome Settings. Yet it shows the error. I would think the problem might be in gsettings package.
![Peek 2022-01-12 16-02](https://user-images.githubusercontent.com/1629120/149176535-9dc1e597-f3d8-4597-b489-5de9ad6efb5f.gif)

**Comment by Feichtmeier** [comment]
Strange - something changed from 20.04 (where you've developed this) to 21.10 regarding the schema? I have no idea really the schema is there and they keys are the same AND it does what it should do :shrug:

**Comment by mivoligo** [comment]
gsettings changed :smile: I'll try to create a minimal app to reproduce this and see if there's the same issue.

**Comment by Feichtmeier** [comment]
this is caused by vscode
