### ISSUE TITLE
Cannot open app 

### ISSUE THREAD

**Issue by Adithyan007hack** [ubuntu-flutter-community/settings#347]
I am unable to open the app it is giving me a error output in terminal
``
./software: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./software)``
The Distro is zorin 16 (ubuntu 20.04)
can anybody help me

**Comment by Feichtmeier** [comment]
hi, I've deleloped this on 22.04 with flutter and it's debian deps. So this might be the issue for you on 20.04
If I get to release this app as a snap you won't have this problem anymore.
