### ISSUE TITLE
SeeingSection: create enum and localize

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu-flutter-community/settings#376]
https://github.com/ubuntu-flutter-community/settings/blob/6b12d14f1f685987ec680bab5ef2f6d8a9bb5b9e/lib/view/pages/accessibility/accessibility_model.dart#L201-L207

Could be an enum instead 

```dart
enum ScreenPosition {
    fullScreen,
    topHalf,
    bottomHalf,
    leftHalf,
    rightHalf;

String localize(AppLocalization l10n) {
  switch(this) {
   case fullScreen:
     return l10n.........
    }
  }
}
```

then you do not need to fiddle with replace all here

https://github.com/ubuntu-flutter-community/settings/blob/6b12d14f1f685987ec680bab5ef2f6d8a9bb5b9e/lib/view/pages/accessibility/seeing_section.dart#L271-L299

:) Thanks in advance and as always - no stress :)

**Comment by mivoligo** [comment]
#392
