### ISSUE TITLE
WallpaperPage: Add the title and copyright info

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu-flutter-community/settings#385]

**Comment by Feichtmeier** [comment]
@YoussefLasheen could you fix this one? :smile_cat:

**Comment by YoussefLasheen** [comment]
@Feichtmeier Sure! :smile:

**Comment by YoussefLasheen** [comment]
Should this issue be closed now? @Feichtmeier

**Comment by Feichtmeier** [comment]
Yes thank you for working on this! :) 
Just add

Fixes # 123124
or
Closes # 123124

to every pull request description (without the space after the #)
