### ISSUE TITLE
Hide back button from the expanded view

### ISSUE THREAD

**Issue by YoussefLasheen** [ubuntu-flutter-community/settings#401]
The back button serves no purpose in the expanded view and currently does nothing.

Expanded view
![Screenshot from 2022-11-23 01-17-16](https://user-images.githubusercontent.com/28854622/203440742-8838c0a6-c3de-4f2d-91af-22d4583e9645.png)

Retracted view
![Screenshot from 2022-11-23 01-17-57](https://user-images.githubusercontent.com/28854622/203440749-1a63c145-f72c-4cb1-9650-0a9a6a3cc03e.png)

**Comment by Feichtmeier** [comment]
@Jupi007 is this something new from the new release?

**Comment by Feichtmeier** [comment]
This must be something new from changes happening in yaru widgets

here 
https://ubuntu.github.io/yaru_widgets.dart/
everything is fine, so I guess we need to adapt settings to the new version

things are currently moving so fast in yaru widgets that I don't always manage to keep up :)
