### ISSUE TITLE
Picture of the day doesn't update wallpaper

### ISSUE THREAD

**Issue by Jupi007** [ubuntu-flutter-community/settings#404]
Currently, select an image of the day doesn't update the wallpaper.
Using #403, the caption is still updated.
The refresh button doesn't help more.

![Capture d’écran du 2022-11-25 19-42-32](https://user-images.githubusercontent.com/36476595/204059410-a0745090-b7dc-4737-a28b-583f18561424.png)

Tested with Ubuntu 22.10

CC @YoussefLasheen if you want to grab this :)

**Comment by YoussefLasheen** [comment]
I would love to work on it. 
The model only updates the light mode wallpaper. So the proposed solution is to just set both pictureUri and pictureUriDark to the wallpaper.

**Comment by Jupi007** [comment]
Okay, so this is related to the dark mode.
That you propose can be a temp fix, but I think that directly add support for dark mode wallpaper could be nicer. 
WDYT?

**Comment by YoussefLasheen** [comment]
I think the expected behavior is for the wallpaper to be set regardless of the theme mode. I would love your input on how would supporting dark mode would be like.

**Comment by Jupi007** [comment]
> I think the expected behavior is for the wallpaper to be set regardless of the theme mode. I would love your input on how would supporting dark mode would be like.

I think remember that gnome control center support this feature of wallpaper depending on the theme mode.
That we could do, is add a switch button like: "Same wallpaper on light/dark mode".
If on, the wallpaper will be set for both themes. And if off, it will be set only for the current theme (with an additional caption like: "light mode wallpaper").

**Comment by YoussefLasheen** [comment]
I think that's a cool feature. But that wouldn't work for the ImageOfTheDay mode though.  Maybe it'll work for the custom and colored background. 
If  you opened an issue for this feature I will work on it.

**Comment by Jupi007** [comment]
Btw, I noticed that the image of the day doesn't keep its state, as it switch to the wallpaper mode when you reload the page.
So maybe this feature should be merged in the wallpaper mode in a kind of "get image of the day" button.
I think it would be less confusing.

But that's another topic :)

**Comment by YoussefLasheen** [comment]
Colored background doesn't keep it's state too.
The current wallpaper model doesn't have a way to store settings that are not part of the gsettings protocol. I had to embed the copyright info in the wallpaper name to save it across reloads. 
We could do the same by checking the path of the wallpaper to determine the current mode.

**Comment by Jupi007** [comment]
> We could do the same by checking the path of the wallpaper to determine the current mode.

Good idea, that would be the best solution :+1: 
Find a way to keep the colored wallpaper mode could be also very nice.
