### ISSUE TITLE
Wallpaper page: add dark mode support

### ISSUE THREAD

**Issue by Jupi007** [ubuntu-flutter-community/settings#406]
In the current state, the wallpaper is defined for both dark/light theme.
GS supports to have different wallpaper depending on the theme, and it would be nice to add this feature here.

CC @YoussefLasheen if you want to grab it :)

**Comment by shan-shaji** [comment]
@Jupi007 can i take a look at this? I would like to get a little more details and what should be the behaviour that i should achieve.

**Comment by Jupi007** [comment]
@shan-shaji ofc you can 🙂

**Comment by shan-shaji** [comment]
ok thank you @Jupi007

**Comment by shan-shaji** [comment]
@Jupi007 can i please get a bit more context about the feature?

**Comment by Feichtmeier** [comment]
basically when you set the wallpaper from the chosen file you need to check what the current theme is and change the gsettings key corresponding to this

**Comment by shan-shaji** [comment]
@Feichtmeier , i am not that much familiar with gsettings. Really sorry..  do we have any docs?

**Comment by Feichtmeier** [comment]
Sadly not many docs but you can check what WallpaperModel does and at some point it sets the wallpaper, I think I remember you only need to make a case for the dark wallpaper there

**Comment by Jupi007** [comment]
Currently, the wallpaper is set twice: once for light theme once for the dark one.

**Comment by shan-shaji** [comment]
Got it

**Comment by shan-shaji** [comment]
@Jupi007 but i think the current behaviour supports different wallpaper depending on the theme.

**Comment by shan-shaji** [comment]
![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/42430941/216781809-ab876830-2301-4322-9dc5-85ed83c8a2be.gif)

**Comment by Feichtmeier** [comment]
Nice 👍🙂

**Comment by Jupi007** [comment]
Closing, as this feature has been added in #321
