### ISSUE TITLE
WallpaperPage: fix unsplash error

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu-flutter-community/settings#416]
![grafik](https://user-images.githubusercontent.com/15329494/204655944-cb46f64f-f638-4ffe-bf6d-7efecbb7725b.png)

I think the getImageUrl callback ismissing @YoussefLasheen :)

**Comment by YoussefLasheen** [comment]
I think the error is unrelated. I made the callback optional as its not needed for unsplash's api.

**Comment by YoussefLasheen** [comment]
Looks like the unsplash API itself is not that reliable. 
https://source.unsplash.com/1920x1080/daily returns 
![image](https://user-images.githubusercontent.com/28854622/204661658-488873c5-17f5-4a37-9d0e-7f1e1c70f6e0.png)
The model currently trusts the API to return an image so it just saves the response.

**Comment by YoussefLasheen** [comment]
I think the issue with unsplash is resolved now.  @Feichtmeier

**Comment by Feichtmeier** [comment]
Thanks!
