### ISSUE TITLE
Missing page: apps administration

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu-flutter-community/settings#57]
Must-have-features:

- enable/disable specific access rights for resources (snaps/flatpaks)
- manage file handlers for the app
- setup start-up apps

To-be-discussed-features:

- enable/disable notifications

Relevant implementations:
- GCC ![apps](https://user-images.githubusercontent.com/15329494/133434694-e95bb377-8014-435d-b6a9-6afbd916feb0.gif)
![grafik](https://user-images.githubusercontent.com/15329494/133888045-64b6d812-3e3a-44b2-820c-fe4c3450572e.png)
- Windows11

Opinion: I really think this page needs a much better design compared to GCC (would be cool to see what windows11 does here)...
1) I don't think we should use sub-menus at all, as it is confusing to navigate through
2) I am not sure if we need two places to manage notifications (notification page/apps page)

**Comment by mivoligo** [comment]
I can't see Windows 11 screenshot in your post :thinking:

**Comment by Feichtmeier** [comment]
I left those empty in many issues because I can not find pictures of the windows11 setting and I do not have it installed yet :(

**Comment by mivoligo** [comment]
ah, ok, I thought it's something wrong with github
